<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BackupSaves.Core\BackupSaves.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="TaskScheduler" Version="2.12.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SatelliteResourceLanguages>ru</SatelliteResourceLanguages>
  </PropertyGroup>

</Project>
